version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle
    restart: always
    ports:
      - 1521:1521
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_PASSWORD: oracle
    
    volumes:
      - ./data:/opt/oracle/oradata
